-- Chute Plataforma 1.0 - equipos y plantillas oficiales
-- Ejecutar después de 01_schema.sql.

insert into teams (id, name, short_name, badge, tone, coach, logo_path, is_official) values
  ('trucha', 'Sporting La Trucha', 'La Trucha', 'ST', 'azul', 'Bruno Benítez', '/team-logos/trucha.png', true),
  ('guanaco', 'C.S.D El Guanaco', 'El Guanaco', 'EG', 'rojo', 'Hank Romano', '/team-logos/guanaco.png', true),
  ('pantera', 'Atlético Pantera', 'Pantera', 'AP', 'morado', 'Nina Taylor', '/team-logos/pantera.png', true),
  ('parrilla', 'La Parrilla F.C.', 'La Parrilla', 'LP', 'naranja', 'Barry Mack', '/team-logos/parrilla.png', true),
  ('perla', 'La Perla United', 'La Perla', 'PU', 'celeste', 'Cornelius Waters', '/team-logos/perla.png', true),
  ('polpetta', 'Sportivo La Polpetta', 'La Polpetta', 'SP', 'verde', 'Giuseppe Perlatore', '/team-logos/polpetta.png', true)
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  badge = excluded.badge,
  tone = excluded.tone,
  coach = excluded.coach,
  logo_path = excluded.logo_path,
  is_official = excluded.is_official;

insert into team_players (team_id, player_name, position, photo_path) values
  ('trucha', 'Eddy Pino', 'Arquero', '/player-photos/trucha/eddy-pino.png'),
  ('trucha', 'Burt McCloskey', 'Defensa', '/player-photos/trucha/burt-mccloskey.png'),
  ('trucha', 'Dominic Mortensen', 'Defensa', '/player-photos/trucha/dominic-mortensen.png'),
  ('trucha', 'Donald Ortega', 'Defensa', '/player-photos/trucha/donald-ortega.png'),
  ('trucha', 'Mario Luna', 'Defensa', '/player-photos/trucha/mario-luna.png'),
  ('trucha', 'Angelo Carboni', 'Medio', '/player-photos/trucha/angelo-carboni.png'),
  ('trucha', 'Jerold Bogan', 'Medio', '/player-photos/trucha/jerold-bogan.png'),
  ('trucha', 'Kelly Rivera', 'Medio', '/player-photos/trucha/kelly-rivera.png'),
  ('trucha', 'Wilfredo Fernandez', 'Medio', '/player-photos/trucha/wilfredo-fernandez.png'),
  ('trucha', 'Boris Lentz', 'Delantero', '/player-photos/trucha/boris-lentz.png'),
  ('trucha', 'Dino Richi', 'Delantero', '/player-photos/trucha/dino-richi.png'),
  ('trucha', 'Eric Perry', 'Delantero', '/player-photos/trucha/eric-perry.png'),
  ('trucha', 'Faustino Soriano', 'Delantero', '/player-photos/trucha/faustino-soriano.png'),
  ('trucha', 'Ricky Watkins', 'Delantero', '/player-photos/trucha/ricky-watkins.png'),
  ('guanaco', 'Rosendo Acosta', 'Arquero', '/player-photos/guanaco/rosendo-acosta.png'),
  ('guanaco', 'Bo de la Rosa', 'Defensa', '/player-photos/guanaco/bo-de-la-rosa.png'),
  ('guanaco', 'Carmelo Wilkinson', 'Defensa', '/player-photos/guanaco/carmelo-wilkinson.png'),
  ('guanaco', 'Robbie Solomon', 'Defensa', '/player-photos/guanaco/robbie-solomon.png'),
  ('guanaco', 'Warner Ferrera', 'Defensa', '/player-photos/guanaco/warner-ferrera.png'),
  ('guanaco', 'Chuck Chong', 'Medio', '/player-photos/guanaco/chuck-chong.png'),
  ('guanaco', 'Donovan Vinson', 'Medio', '/player-photos/guanaco/donovan-vinson.png'),
  ('guanaco', 'Harley Peralta', 'Medio', '/player-photos/guanaco/harley-peralta.png'),
  ('guanaco', 'Wilton Blackwood', 'Medio', '/player-photos/guanaco/wilton-blackwood.png'),
  ('guanaco', 'Davis Bronson', 'Delantero', '/player-photos/guanaco/davis-bronson.png'),
  ('guanaco', 'Irwin Medeiros', 'Delantero', '/player-photos/guanaco/irwin-medeiros.png'),
  ('guanaco', 'Lonny Ventura', 'Delantero', '/player-photos/guanaco/lonny-ventura.png'),
  ('guanaco', 'Sid Koslowski', 'Delantero', '/player-photos/guanaco/sid-koslowski.png'),
  ('guanaco', 'Sonny Saldana', 'Delantero', '/player-photos/guanaco/sonny-saldana.png'),
  ('pantera', 'Rita Malone', 'Arquero', '/player-photos/pantera/rita-malone.png'),
  ('pantera', 'Belinda Sparks', 'Defensa', '/player-photos/pantera/belinda-sparks.png'),
  ('pantera', 'Mandy Wallace', 'Defensa', '/player-photos/pantera/mandy-wallace.png'),
  ('pantera', 'Nora Cruz', 'Defensa', '/player-photos/pantera/nora-cruz.png'),
  ('pantera', 'Sabrina Mendoza', 'Defensa', '/player-photos/pantera/sabrina-mendoza.png'),
  ('pantera', 'Lina Yamamoto', 'Medio', '/player-photos/pantera/lina-yamamoto.png'),
  ('pantera', 'Margaret Castillo', 'Medio', '/player-photos/pantera/margaret-castillo.png'),
  ('pantera', 'Rebeca Sanders', 'Medio', '/player-photos/pantera/rebeca-sanders.png'),
  ('pantera', 'Sherry Terry', 'Medio', '/player-photos/pantera/sherry-terry.png'),
  ('pantera', 'Cindy Fitzgerald', 'Delantero', '/player-photos/pantera/cindy-fitzgerald.png'),
  ('pantera', 'Jackie Sanchez', 'Delantero', '/player-photos/pantera/jackie-sanchez.png'),
  ('pantera', 'Nancy King', 'Delantero', '/player-photos/pantera/nancy-king.png'),
  ('pantera', 'Roxie Jones', 'Delantero', '/player-photos/pantera/roxie-jones.png'),
  ('pantera', 'Sharon Ortiz', 'Delantero', '/player-photos/pantera/sharon-ortiz.png'),
  ('parrilla', 'Alex Meres', 'Arquero', '/player-photos/parrilla/alex-meres.png'),
  ('parrilla', 'Arthur Turok', 'Defensa', '/player-photos/parrilla/arthur-turok.png'),
  ('parrilla', 'Freddy Manfredo', 'Defensa', '/player-photos/parrilla/freddy-manfredo.png'),
  ('parrilla', 'Joe Pavo', 'Defensa', '/player-photos/parrilla/joe-pavo.png'),
  ('parrilla', 'John Giovanni', 'Defensa', '/player-photos/parrilla/john-giovanni.png'),
  ('parrilla', 'Claudio Conde', 'Medio', '/player-photos/parrilla/claudio-conde.png'),
  ('parrilla', 'El Profesor', 'Medio', '/player-photos/parrilla/el-profesor.png'),
  ('parrilla', 'Peta Zeta', 'Medio', '/player-photos/parrilla/peta-zeta.png'),
  ('parrilla', 'Rod Lete', 'Medio', '/player-photos/parrilla/rod-lete.png'),
  ('parrilla', 'Rolando Akira', 'Medio', '/player-photos/parrilla/rolando-akira.png'),
  ('parrilla', 'El Guaton Nelson', 'Delantero', '/player-photos/parrilla/el-guaton-nelson.png'),
  ('parrilla', 'Luis Felipe', 'Delantero', '/player-photos/parrilla/luis-felipe.png'),
  ('parrilla', 'Nick Cabezon', 'Delantero', '/player-photos/parrilla/nick-cabezon.png'),
  ('parrilla', 'Randolph D''Luna', 'Delantero', '/player-photos/parrilla/randolph-dluna.png'),
  ('perla', 'Eusebio Flowers', 'Arquero', '/player-photos/perla/eusebio-flowers.png'),
  ('perla', 'Edison Cabrera', 'Defensa', '/player-photos/perla/edison-cabrera.png'),
  ('perla', 'Jacinto Chavarria', 'Defensa', '/player-photos/perla/jacinto-chavarria.png'),
  ('perla', 'Lucius Chase', 'Defensa', '/player-photos/perla/lucius-chase.png'),
  ('perla', 'Melvin Clayton', 'Defensa', '/player-photos/perla/melvin-clayton.png'),
  ('perla', 'Archie Jackson', 'Medio', '/player-photos/perla/archie-jackson.png'),
  ('perla', 'Eric Reyes', 'Medio', '/player-photos/perla/eric-reyes.png'),
  ('perla', 'Sammy Portillo', 'Medio', '/player-photos/perla/sammy-portillo.png'),
  ('perla', 'Toyo Takahashi', 'Medio', '/player-photos/perla/toyo-takahashi.png'),
  ('perla', 'El Kraken', 'Delantero', '/player-photos/perla/el-kraken.png'),
  ('perla', 'Julio Vega', 'Delantero', '/player-photos/perla/julio-vega.png'),
  ('perla', 'Marty Love', 'Delantero', '/player-photos/perla/marty-love.png'),
  ('perla', 'Omar Watson', 'Delantero', '/player-photos/perla/omar-watson.png'),
  ('perla', 'Randolph Salazar', 'Delantero', '/player-photos/perla/randolph-salazar.png'),
  ('perla', 'Steven Ramos', 'Delantero', '/player-photos/perla/steven-ramos.png'),
  ('polpetta', 'Vito Volta', 'Arquero', '/player-photos/polpetta/vito-volta.png'),
  ('polpetta', 'Enzo Mancini', 'Defensa', '/player-photos/polpetta/enzo-mancini.png'),
  ('polpetta', 'Fabio Clemenza', 'Defensa', '/player-photos/polpetta/fabio-clemenza.png'),
  ('polpetta', 'Giorgio Valentino', 'Defensa', '/player-photos/polpetta/giorgio-valentino.png'),
  ('polpetta', 'Rocco Carusso', 'Defensa', '/player-photos/polpetta/rocco-carusso.png'),
  ('polpetta', 'Donnie Spumoni', 'Medio', '/player-photos/polpetta/donnie-spumoni.png'),
  ('polpetta', 'Fiorino Panicucci', 'Medio', '/player-photos/polpetta/fiorino-panicucci.png'),
  ('polpetta', 'Mario De Luca', 'Medio', '/player-photos/polpetta/mario-de-luca.png'),
  ('polpetta', 'Milo Gorgazzi', 'Medio', '/player-photos/polpetta/milo-gorgazzi.png'),
  ('polpetta', 'Alessandro Zito', 'Delantero', '/player-photos/polpetta/alessandro-zito.png'),
  ('polpetta', 'Freddo Bellini', 'Delantero', '/player-photos/polpetta/freddo-bellini.png'),
  ('polpetta', 'Giulio Locatelli', 'Delantero', '/player-photos/polpetta/giulio-locatelli.png'),
  ('polpetta', 'Nicola Pisani', 'Delantero', '/player-photos/polpetta/nicola-pisani.png'),
  ('polpetta', 'Paolo Fontana', 'Delantero', '/player-photos/polpetta/paolo-fontana.png')
on conflict (team_id, player_name) do update set
  position = excluded.position,
  photo_path = excluded.photo_path;
